# 🚀 Coolify Configuration for Luna Platform
# PowerPoint Processing Platform with AI Capabilities

version: "3.8"

services:
  luna:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      # Core Configuration
      NODE_ENV: production
      PORT: 3000
      
      # File Processing Limits
      MAX_FILE_SIZE: 62914560
      UPLOAD_TEMP_DIR: /app/temp/uploads
      ASPOSE_TEMP_DIR: /app/temp/aspose
      
      # Java Runtime Configuration
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      JAVA_OPTS: "-Xmx2g -Xms512m -Djava.awt.headless=true"
      
      # Aspose.Slides Local Library
      ASPOSE_LICENSE_PATH: /app/Aspose.Slides.Product.Family.lic
      
      # Firebase Configuration
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-4-turbo-preview
      
      # Security Configuration
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      JWT_SECRET: ${JWT_SECRET}
      
    volumes:
      - luna_uploads:/app/temp/uploads
      - luna_aspose:/app/temp/aspose
      - luna_conversions:/app/temp/conversions
      - luna_logs:/app/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  luna_uploads:
  luna_aspose:
  luna_conversions:
  luna_logs: 