# 📊 Prometheus Configuration for Luna Platform
# Comprehensive monitoring of all services and infrastructure

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files
rule_files:
  - "alert.rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Add alertmanager if needed
          # - alertmanager:9093

# Scrape configurations
scrape_configs:
  # =============================================================================
  # INFRASTRUCTURE MONITORING
  # =============================================================================
  
  # System metrics (CPU, Memory, Disk, Network)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # =============================================================================
  # LUNA APPLICATION MONITORING
  # =============================================================================
  
  # Luna Backend API (Node.js)
  - job_name: 'luna-backend'
    static_configs:
      - targets: ['luna-server:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Luna Frontend (nginx metrics if available)
  - job_name: 'luna-frontend'
    static_configs:
      - targets: ['luna-client:80']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Nginx Proxy
  - job_name: 'nginx-proxy'
    static_configs:
      - targets: ['luna-nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # =============================================================================
  # APPLICATION HEALTH CHECKS
  # =============================================================================
  
  # Backend health monitoring
  - job_name: 'luna-health-backend'
    static_configs:
      - targets: ['luna-server:3000']
    metrics_path: /api/v1/health
    scrape_interval: 30s
    scrape_timeout: 10s

  # Frontend health monitoring
  - job_name: 'luna-health-frontend'
    static_configs:
      - targets: ['luna-client:80']
    metrics_path: /
    scrape_interval: 30s
    scrape_timeout: 5s

  # Nginx health monitoring
  - job_name: 'luna-health-nginx'
    static_configs:
      - targets: ['luna-nginx:80']
    metrics_path: /nginx-health
    scrape_interval: 30s
    scrape_timeout: 5s

  # =============================================================================
  # EXTERNAL MONITORING (if accessible)
  # =============================================================================
  
  # Monitor external services if needed
  # - job_name: 'external-api'
  #   static_configs:
  #     - targets: ['api.external-service.com:443']
  #   scheme: https
  #   scrape_interval: 60s

# =============================================================================
# METRIC RELABELING (Optional)
# =============================================================================

# Global relabeling can be added here if needed 