# =============================================================================
# Luna Server - Development Docker Compose
# 
# Development setup with hot reloading and debugging support
# =============================================================================

version: '3.8'

services:
  # =============================================================================
  # Development Application Service
  # =============================================================================
  luna-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: luna-server-dev
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
      - "9229:9229"  # Node.js debugging port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_VERSION=${API_VERSION:-v1}
      
      # File Processing
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}
      - BODY_PARSER_LIMIT=${BODY_PARSER_LIMIT:-50mb}
      - ASPOSE_TEMP_DIR=/app/temp/aspose
      - UPLOAD_TEMP_DIR=/app/temp/uploads
      - ASPOSE_LICENSE_PATH=${ASPOSE_LICENSE_PATH:-./Aspose.Slides.Product.Family.lic}
      
      # External Services
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIRESTORE_DATABASE_URL=${FIRESTORE_DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Features
      - FEATURE_FIREBASE_STORAGE=${FEATURE_FIREBASE_STORAGE:-true}
      - FEATURE_AI_TRANSLATION=${FEATURE_AI_TRANSLATION:-true}
      - FEATURE_AI_ANALYSIS=${FEATURE_AI_ANALYSIS:-true}
      
      # Development
      - CORS_ORIGIN=http://localhost:3000,http://localhost:5173,http://localhost:8080
      - DEBUG=luna:*
      - LOG_LEVEL=debug
      
      # Redis
      - REDIS_URL=redis://redis-dev:6379
    volumes:
      - .:/app
      - /app/node_modules  # Anonymous volume for node_modules
      - ./temp:/app/temp
      - ./logs:/app/logs
    networks:
      - luna-dev-network
    depends_on:
      redis-dev:
        condition: service_healthy
    command: ["npm", "run", "dev"]

  # =============================================================================
  # Redis Service (Development)
  # =============================================================================
  redis-dev:
    image: redis:7-alpine
    container_name: luna-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - luna-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # =============================================================================
  # Redis Commander (GUI for Redis)
  # =============================================================================
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: luna-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis-dev:6379
    networks:
      - luna-dev-network
    depends_on:
      - redis-dev

  # =============================================================================
  # File Browser (Development File Management)
  # =============================================================================
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: luna-filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./temp:/srv/temp
      - ./logs:/srv/logs
      - ./volumes:/srv/volumes
    environment:
      - FB_NOAUTH=true
    networks:
      - luna-dev-network

# =============================================================================
# Networks
# =============================================================================
networks:
  luna-dev-network:
    driver: bridge

# =============================================================================
# Volumes
# =============================================================================
volumes:
  redis-dev-data:
    driver: local 