global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Luna Server Application Metrics
  - job_name: 'luna-server'
    static_configs:
      - targets: ['luna-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    labels:
      service: 'luna-server'
      environment: 'production'

  # Luna Client Application Metrics
  - job_name: 'luna-client'
    static_configs:
      - targets: ['luna-client:5173']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    labels:
      service: 'luna-client'
      environment: 'development'

  # Node Exporter - System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s
    labels:
      service: 'node-exporter'
      type: 'system'

  # cAdvisor - Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    labels:
      service: 'cadvisor'
      type: 'container'

  # Loki Metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'loki'
      type: 'logging'

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'grafana'
      type: 'visualization'

  # Docker Engine Metrics (if docker daemon metrics are enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'docker'
      type: 'infrastructure'

  # Custom Luna Platform Metrics
  - job_name: 'luna-custom-metrics'
    static_configs:
      - targets: ['luna-server:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    labels:
      service: 'luna-custom'
      type: 'application'

  # Health Check Monitoring
  - job_name: 'health-checks'
    static_configs:
      - targets: 
          - 'luna-server:3000'
          - 'luna-client:5173'
    metrics_path: '/health'
    scrape_interval: 15s
    scrape_timeout: 5s
    labels:
      type: 'health'

  # Aspose.Slides Processing Metrics (if available)
  - job_name: 'aspose-metrics'
    static_configs:
      - targets: ['luna-server:3000']
    metrics_path: '/api/v1/aspose/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s
    labels:
      service: 'aspose-slides'
      type: 'processing'

  # Firebase/Firestore Metrics (if available)
  - job_name: 'firebase-metrics'
    static_configs:
      - targets: ['luna-server:3000']
    metrics_path: '/api/v1/firebase/metrics'
    scrape_interval: 60s
    labels:
      service: 'firebase'
      type: 'database' 